# nginx
---

- include: package_selection.yml

- user: name="{{run_user}}" shell=/usr/sbin/nologin

- name: Install packages
  package: name={{ item }} state=installed
  with_items: "{{ nginx_packages }}"

- name: turn off PHP output buffering
  ini_file: dest="/etc/{{php_name}}/fpm/php.ini" section=PHP option=output_buffering value=Off
  notify:
    - start php-fpm
    - restart nginx

- name: use port instead of local socket for php-fpm
  ini_file: dest="/etc/{{php_name}}/fpm/pool.d/www.conf" section=www option=listen value=9000
  notify:
    - start php-fpm
    - restart nginx

- name: Apply config template
  template:
    src: works.conf
    dest: "/etc/nginx/sites-available/default"

- name: enable mcrypt
  shell: "{{php_name}}enmod mcrypt"

- name: Enable nginx conf
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: link
    src: "/etc/nginx/sites-available/default"
  notify:
    - start php-fpm
    - restart nginx
