---
sudo: required

env:
  - distribution: centos
    version: 7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_opts: ""
  - distribution: ubuntu
    version: 16.04
    init: /sbin/init
    run_opts: ""
  - distribution: ubuntu
    version: 17.04
    init: /sbin/init
    run_opts: ""
  - distribution: debian
    version: 8
    init: /sbin/init
    run_opts: ""
  - distribution: debian
    version: 9
    init: /sbin/init
    run_opts: ""

services:
  - docker

before_install:
  # Pull container
  - 'sudo docker pull ${distribution}:${version}'
  # Customize container
  - 'sudo docker build --rm=true --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests'

script:
  - container_id=$(mktemp)
  # Run container in detached state.
  - 'sudo docker run --detach --volume="${PWD}":/mnt:ro ${run_opts} ${distribution}-${version}:ansible "${init}" > "${container_id}"'

  # run setup to sanity check
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ls -la /mnt'

  # run setup to sanity check
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible all -m setup'

  # Install required Galaxy roles.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-galaxy install -r /mnt/requirements.yml'

  # Ansible syntax check.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm bash -c "cd /mnt/tests ; ansible-playbook test.yml --syntax-check"'

  # Test role.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm bash -c "cd /mnt/tests ; ansible-playbook test.yml"'
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm bash -c "cd /mnt/tests ; ansible-playbook test.yml"'

  # Test role idempotence.
  - >
    sudo docker exec "$(cat ${container_id})" bash -c "cd /mnt/tests ; ansible-playbook test.yml"
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  # Clean up
  - 'sudo docker stop "$(cat ${container_id})"'
