FROM ubuntu:14.04
RUN apt-get update

# Install Ansible
RUN apt-get install dbus python-pip python-dev git python-yaml python-paramiko -y
RUN pip install jinja2

RUN cd ~ && \
    git clone https://github.com/ansible/ansible.git && \
    cd ansible && \
    git checkout v2.3.0.0-1 && \
    git submodule update --init --recursive && \
    make install && \
    mkdir /etc/ansible

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

RUN ln -s /lib/systemd/system/systemd-logind.service /etc/systemd/system/multi-user.target.wants/systemd-logind.service
RUN mkdir /etc/systemd/system/sockets.target.wants/
RUN ln -s /lib/systemd/system/dbus.socket /etc/systemd/system/sockets.target.wants/dbus.socket
