---
- name: ffmpeg ppa for ubuntu 14.04
  apt_repository: repo='ppa:mc3man/trusty-media'
  when: ansible_distribution=="Ubuntu" and ansible_distribution_version | version_compare('14.04', '==')

- name: ffmpeg ppa for ubuntu 16.04
  apt_repository: repo='ppa:jonathonf/ffmpeg-3'
  when: ansible_distribution=="Ubuntu" and ansible_distribution_version | version_compare('16.04', '==')

- name: ffmpeg repo jessie
  apt_repository:
    repo: "deb http://www.deb-multimedia.org jessie main non-free"
    state: present
    filename: deb_multimedia
  when: ansible_distribution=="Debian" and ansible_distribution_major_version | version_compare('8', '==')

- name: ffmpeg repo jessie backports
  apt_repository:
    repo: "deb http://www.deb-multimedia.org jessie-backports main"
    state: present
    filename: deb_multimedia
    update_cache: true
  when: ansible_distribution=="Debian" and ansible_distribution_major_version | version_compare('8', '==')

- name: ffmpeg repo stretch
  apt_repository:
    repo: "deb http://www.deb-multimedia.org stretch main non-free"
    state: present
    filename: deb_multimedia
    update_cache: true
  when: ansible_distribution=="Debian" and ansible_distribution_major_version | version_compare('9', '==')

- name: install ffmpeg
  apt: name=ffmpeg state=installed update_cache=yes force=true
  when: ansible_distribution=="Debian" or ansible_distribution=="Ubuntu"

# https://www.vultr.com/docs/how-to-install-ffmpeg-on-centos
# On CentOS 7, you can install the Nux Dextop YUM repo with the following commands:
#
# sudo rpm --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
# sudo rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
# For CentOS 6, you need to install another release:
#
# sudo rpm --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
# sudo rpm -Uvh http://li.nux.ro/download/nux/dextop/el6/x86_64/nux-dextop-release-0-2.el6.nux.noarch.rpm

- name: Install nux desktop key
  shell: rpm --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
  when: ansible_os_family == 'RedHat'

- name: Add nux desktop rep for el 7
  yum:
    name: "http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm"
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == "7"

- name: Add nux desktop rep for el 6
  yum:
    name: "http://li.nux.ro/download/nux/dextop/el6/x86_64/nux-dextop-release-0-2.el6.nux.noarch.rpm"
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == "6"

- name: install ffmpeg Redhat
  package: name=ffmpeg state=installed
  when: ansible_os_family == 'RedHat'
