---
- include: ffmeg.yml

- name: copy ruTorrent update script
  copy: src=update-rutorrent dest=/usr/local/bin/update-rutorrent mode=0777 force=yes

- name: Make ruTorrent directory
  file:
    name: "{{ rutorrent_install_dir }}"
    state: directory

# - name: Download ruTorrent to /var/www/rutorrent
#   command: bash -e /usr/local/bin/update-rutorrent
#   args:
#     creates: /var/www/rutorrent/conf

- file: path="/usr/share/pydio" state=absent

- name: Checkout ruTorrent from git
  git: repo=https://github.com/Novik/ruTorrent.git dest="{{ rutorrent_install_dir }}" force=true
  changed_when: false

- name: Checkout ruTorrent plugins
  git:
    repo: "https://github.com/nelu/rutorrent-thirdparty-plugins.git"
    dest: "{{ rutorrent_install_dir_tmp }}"

- name: move plugins in place
  shell: "cp -R {{ rutorrent_install_dir_tmp }}/* {{ rutorrent_install_dir }}/plugins"
  changed_when: false

- name: Checkout ruTorrent mobile from git
  git:
    repo: https://github.com/xombiemp/rutorrentMobile.git
    dest: "{{ rutorrent_install_dir }}/plugins/mobile"

- name: Apply config template
  template: src=config.php dest="{{ rutorrent_install_dir }}/conf/config.php" owner=www-data group=www-data
  changed_when: false

- name: Copy autowatch config file
  copy: src=autotools-conf.php dest="{{ rutorrent_install_dir }}/plugins/autotools/conf.php" force=yes
  changed_when: false

- name: Copy screenshots config file
  copy: src=screenshots-conf.php dest="{{ rutorrent_install_dir }}/plugins/screenshots/conf.php" force=yes
  changed_when: false

- name: Copy unpack config file
  copy: src=unpack-conf.php dest="{{ rutorrent_install_dir }}/plugins/unpack/conf.php" force=yes
  changed_when: false

- name: Create password
  command: "htpasswd -cb /etc/nginx/passwd {{ web_user }} {{ web_password }}"
  when: web_user is defined
  changed_when: false

- name: Copy over html files
  copy: src=auth.tar.gz dest=/tmp/auth.tar.gz

- name: Extract auth components
  command: "/usr/bin/bsdtar -xf /tmp/auth.tar.gz --strip-components 1"
  args:
    creates: "/var/www/login.html"
    chdir: "/var/www"

- name: Set Perms on ruTorrent directory
  file:
    name: /var/www
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  changed_when: false

- name: Set Perms on ruTorrent directory
  file:
    name: /u02
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
