
---
- name: Checkout xmlrpc from subversion
  subversion:
    repo: "http://svn.code.sf.net/p/xmlrpc-c/code/advanced"
    dest: /usr/src/xmlrpc-c

- name: check for successful install
  stat: path=/usr/src/xmlrpc-c/.installed
  register: xmlrpc_installed

- block:

  - name: configure xmlrpc-c
    command: "/bin/sh /usr/src/xmlrpc-c/configure"
    args:
      chdir: /usr/src/xmlrpc-c

  - name: Make xmlrpc-c
    command: "/usr/bin/make"
    args:
      chdir: /usr/src/xmlrpc-c

  - name: Install xmlrpc-c
    command: "/usr/bin/make install"
    args:
      chdir: /usr/src/xmlrpc-c

  - name: Record successful install
    file: path=/usr/src/xmlrpc-c/.installed state=touch
  #End block
  when: xmlrpc_installed.stat.exists
