---
- name: Install packages
  apt: pkg={{ item }} state=installed update_cache=yes
  when: ansible_os_family != 'RedHat'
  with_items:
    - nfs-common

- name: Install packages Redhat
  package: name={{ item }} state=installed
  when: ansible_os_family == 'RedHat'
  with_items:
    - nfs-common

- service: name=rpcbind state=restarted

- group: name=downloads state=present

- user: name="{{run_user}}" shell=/bin/bash groups=downloads append=yes

- name: create nfs mount
  file:
    path: /u01
    state: directory
    mode: "u+rwx,g+rwxs,o-rwx"
    owner: root
    group: downloads
    recurse: true

- mount: name=/u01 src="{{ nfs_server }}:{{ nfs_mount }}" fstype=nfs opts="rw,rsize=8192,wsize=8192,nolock" state=mounted
