---

- name: Install deps and utils
  package: name={{ item }} state=latest
  when: ansible_os_family != 'RedHat'
  with_items:
    - automake
    - build-essential
    - bsdtar
    - curl
    - git-core
    - libav-tools
    - libcppunit-dev
    - libcurl4-openssl-dev
    - libncurses5-dev
    - libsigc++-2.0-dev
    - libtool
    - mediainfo
    - subversion
    - zip
    - unrar-free
    - unzip
    - git

  - name: Install deps and utils
    package: name={{ item }} state=latest
    when: ansible_os_family = 'RedHat'
    with_items:
      - automake
      - bsdtar
      - curl
      - git-core
      - libtool
      - mediainfo
      - subversion
      - zip
      - unzip
      - git
