---

- name: Install deps and utils
  package: name={{ item }} state=latest
  when: ansible_os_family != 'RedHat'
  with_items:
    - automake
    - build-essential
    - bsdtar
    - curl
    - git-core
    - libav-tools
    - libcppunit-dev
    - libcurl4-openssl-dev
    - libncurses5-dev
    - libsigc++-2.0-dev
    - libtool
    - mediainfo
    - subversion
    - zip
    - unrar-free
    - unzip
    - git

- name: Install deps and utils
  package: name={{ item }} state=latest
  when: ansible_os_family == 'RedHat'
  with_items:
    - automake
    - bsdtar
    - curl
    - git-core
    - libtool
    - mediainfo
    - subversion
    - zip
    - unzip
    - git

- user: name=pi shell=/bin/bash groups=downloads append=yes

- name: create nfs mount
  file:
    path: /u01
    state: directory
    mode: "u+rwx,g+rwxs,o-rwx"
    owner: root
    group: downloads
    recurse: true
